---
- name: Configure watchdog device
  when: patroni_watchdog_mode != 'off'
  block:
    - name: Give postgres access to the watchdog device
      ansible.builtin.template:
        src: 99-patroni-watchdog.rules.j2
        dest: /etc/udev/rules.d/99-patroni-watchdog.rules
        owner: root
        group: root
        mode: "0644"
      notify: Apply watchdog udev rule

    - name: Load watchdog kernel module
      community.general.modprobe:
        name: "{{ patroni_watchdog_module }}"
        state: present
        persistent: present
      when: patroni_watchdog_module | length > 0

    - name: Apply udev rule before Patroni starts
      ansible.builtin.meta: flush_handlers
