---
galaxy_info:
  author: DBA team
  description: PostgreSQL server packages and directories (initdb is done by Patroni)
  license: proprietary
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: ["9", "10"]
dependencies: []
