---
postgresql_packages:
  - postgresql{{ pg_major_version }}
  - postgresql{{ pg_major_version }}-server
  - postgresql{{ pg_major_version }}-contrib
postgresql_bin_dir: /usr/pgsql-{{ pg_major_version }}/bin
postgresql_home_dir: /var/lib/pgsql

# Пути к данным и WAL. Монтирование делает команда ОС, роль только создаёт каталоги.
postgresql_data_dir: /var/lib/pgsql/{{ pg_major_version }}/data
postgresql_wal_dir: /var/lib/pgsql/{{ pg_major_version }}/wal
postgresql_unix_socket_dir: /run/postgresql
